FORMAT: 1A

# Fooooty API
The **Fooooty API** is the heart and soul of **Fooooty**.  The API controls everything anyone can do in the game.

# Group Main

## Authenticate [/auth]

### auth [POST]
Gets a web token for use in future calls

+ Response 200

  + Headers

            Content-Type: application/json; charset=utf-8

  + Body

            {
              "token": "XXX"
            }

  + Schema

            {
                "type": "object",
                "required": true,
                "properties": {
                    "token": {
                        "type": ["string"],
                        "required": true
                    }
                }
            }


# Group Players

## Player Basics [/api/v1/players]

### getAllPlayers [GET]
Gets all the players currently in the `players` table.

+ Request

  + Headers

            Content-Type: application/json

+ Response 200

  + Headers

            Content-Type: application/json; charset=utf-8

  + Body

            [
               {
                  "id":1,
                  "club_id":null,
                  "nation_id":0,
                  "first_name":"Autumn",
                  "last_name":"Hand",
                  "suffix":"",
                  "age":0,
                  "starting":0,
                  "level":0,
                  "super_skill":0,
                  "position":"UT",
                  "oop":0,
                  "dp":0,
                  "suspended":0,
                  "health":100,
                  "auction_type":0,
                  "auction_price":0
               },
               {
                  "id":2,
                  "club_id":null,
                  "nation_id":0,
                  "first_name":"Gabriella",
                  "last_name":"Mohr",
                  "suffix":"",
                  "age":0,
                  "starting":0,
                  "level":0,
                  "super_skill":0,
                  "position":"FW",
                  "oop":0,
                  "dp":0,
                  "suspended":0,
                  "health":100,
                  "auction_type":0,
                  "auction_price":0
               },
               {
                  "id": 3,
                  "club_id": 1,
                  "nation_id": 0,
                  "first_name": "Clifton",
                  "last_name": "Kuhic",
                  "suffix": "",
                  "age": 0,
                  "starting": 0,
                  "level": 0,
                  "super_skill": 0,
                  "position": "FW",
                  "oop": 0,
                  "dp": 0,
                  "suspended": 0,
                  "health": 100,
                  "auction_type": 0,
                  "auction_price": 0
                }
            ]


### createPlayer [POST]
Creates a brand new player

+ Request

  + Headers

            Content-Type: application/json

+ Response 200

  + Headers

            Content-Type: application/json; charset=utf-8

  + Body

            {
              "first_name": "Angelita",
              "last_name": "Crona",
              "position": "GK",
              "health": 100,
              "id": 33
            }


## Unsigned Player Listing [/api/v1/players/available]

### getAllUnsignedPlayers [GET]
Gets an array of all unsigned players (limit of 10).

+ Request

  + Headers

            Content-Type: application/json

+ Response 200

  + Headers

            Content-Type: application/json; charset=utf-8

  + Body

            [
               {
                  "id":1,
                  "club_id":null,
                  "nation_id":0,
                  "first_name":"Autumn",
                  "last_name":"Hand",
                  "suffix":"",
                  "age":0,
                  "starting":0,
                  "level":0,
                  "super_skill":0,
                  "position":"UT",
                  "oop":0,
                  "dp":0,
                  "suspended":0,
                  "health":100,
                  "auction_type":0,
                  "auction_price":0
               },
               {
                  "id":2,
                  "club_id":null,
                  "nation_id":0,
                  "first_name":"Gabriella",
                  "last_name":"Mohr",
                  "suffix":"",
                  "age":0,
                  "starting":0,
                  "level":0,
                  "super_skill":0,
                  "position":"FW",
                  "oop":0,
                  "dp":0,
                  "suspended":0,
                  "health":100,
                  "auction_type":0,
                  "auction_price":0
               }
            ]


## Unsigned Player Listing By Position [/api/v1/players/available/{position}]

+ Parameters
    + position (required, string, `FW`) ... Which position do you want to search for

### getAllUnsignedPlayersFromPosition [GET]
Gets an array of all unsigned players that play a specific position (limit of 10).

+ Request

  + Headers

            Content-Type: application/json

+ Response 200

  + Headers

            Content-Type: application/json; charset=utf-8

  + Body

            [
              {
                 "id":2,
                 "club_id":null,
                 "nation_id":0,
                 "first_name":"Gabriella",
                 "last_name":"Mohr",
                 "suffix":"",
                 "age":0,
                 "starting":0,
                 "level":0,
                 "super_skill":0,
                 "position":"FW",
                 "oop":0,
                 "dp":0,
                 "suspended":0,
                 "health":100,
                 "auction_type":0,
                 "auction_price":0
              }
            ]


## Get Player [/api/v1/players/{id}]

+ Parameters
    + id (required, integer, `1`) ... The ID of the player you want

### getPlayer [GET]
Gets full information about a specific player

+ Request

  + Headers

            Content-Type: application/json

+ Response 200

  + Headers

            Content-Type: application/json; charset=utf-8

  + Body

            {
               "id":1,
               "club_id":null,
               "nation_id":0,
               "first_name":"Autumn",
               "last_name":"Hand",
               "suffix":"",
               "age":0,
               "starting":0,
               "level":0,
               "super_skill":0,
               "position":"UT",
               "oop":0,
               "dp":0,
               "suspended":0,
               "health":100,
               "auction_type":0,
               "auction_price":0
            }


## Get Player With Club [/api/v1/players/{id}/clubs]

+ Parameters
    + id (required, integer, `1`) ... The ID of the player you want

### getPlayerWithClub [GET]
Gets full information about a specific player along with the associated club information (if available)

+ Request

  + Headers

            Content-Type: application/json

+ Response 200

  + Headers

            Content-Type: application/json; charset=utf-8

  + Body

            {
              "id": 1,
              "club_id": 1,
              "nation_id": 0,
              "first_name": "Katlynn",
              "last_name": "Schimmel",
              "suffix": "",
              "age": 0,
              "starting": 0,
              "level": 0,
              "super_skill": 0,
              "position": "SW",
              "oop": 0,
              "dp": 0,
              "suspended": 0,
              "health": 100,
              "auction_type": 0,
              "auction_price": 0,
              "club":{
                "id": 1,
                "manager_id": 0,
                "stadium_id": 0,
                "division_id": 0,
                "divisional_position": 0,
                "name": "Cole-Schowalter"
              }
            }

  + Schema

            {
                "type": "object",
                "required": true,
                "properties": {
                    "club": {
                        "type": ["object"],
                        "required": false
                    }
                }
            }


## Club Membership [/api/v1/players/{id}/clubs/{club_id}]

+ Parameters
    + id (required, integer, `1`) ... The ID of the player you want
    + club_id (required, integer, `1`) ... The ID of the club you want to join

### joinClub [PUT]
Joins a player to a specific club

+ Request

  + Headers

            Content-Type: application/json

+ Response 200

  + Headers

            Content-Type: application/json; charset=utf-8

  + Body

            {
              "id": 1,
              "club_id": 1,
              "nation_id": 0,
              "first_name": "Katlynn",
              "last_name": "Schimmel",
              "suffix": "",
              "age": 0,
              "starting": 0,
              "level": 0,
              "super_skill": 0,
              "position": "SW",
              "oop": 0,
              "dp": 0,
              "suspended": 0,
              "health": 100,
              "auction_type": 0,
              "auction_price": 0
            }

### leaveClub [DELETE]
Leaves a specific club as a player

+ Request

  + Headers

            Content-Type: application/json

+ Response 200

  + Headers

            Content-Type: application/json; charset=utf-8

  + Body

            {
              "id": 1,
              "club_id": null,
              "nation_id": 0,
              "first_name": "Katlynn",
              "last_name": "Schimmel",
              "suffix": "",
              "age": 0,
              "starting": 0,
              "level": 0,
              "super_skill": 0,
              "position": "SW",
              "oop": 0,
              "dp": 0,
              "suspended": 0,
              "health": 100,
              "auction_type": 0,
              "auction_price": 0
            }


## Start Player [/api/v1/players/{id}/start]

+ Parameters
    + id (required, integer, `1`) ... The ID of the player you want

### startPlayer [PUT]
Changes a player to starting, meaning they wil play in the game

+ Request

  + Headers

            Content-Type: application/json

+ Response 200

  + Headers

            Content-Type: application/json; charset=utf-8

  + Body

            {
              "id": 1,
              "club_id": 1,
              "nation_id": 0,
              "first_name": "Katlynn",
              "last_name": "Schimmel",
              "suffix": "",
              "age": 0,
              "starting": 1,
              "level": 0,
              "super_skill": 0,
              "position": "SW",
              "oop": 0,
              "dp": 0,
              "suspended": 0,
              "health": 100,
              "auction_type": 0,
              "auction_price": 0
            }


## Bench Player [/api/v1/players/{id}/bench]

+ Parameters
    + id (required, integer, `1`) ... The ID of the player you want

### benchPlayer [PUT]
Benches a specific player to make them not start in the game

+ Request

  + Headers

            Content-Type: application/json

+ Response 200

  + Headers

            Content-Type: application/json; charset=utf-8

  + Body

            {
              "id": 1,
              "club_id": null,
              "nation_id": 0,
              "first_name": "Katlynn",
              "last_name": "Schimmel",
              "suffix": "",
              "age": 0,
              "starting": 0,
              "level": 0,
              "super_skill": 0,
              "position": "SW",
              "oop": 0,
              "dp": 0,
              "suspended": 0,
              "health": 100,
              "auction_type": 0,
              "auction_price": 0
            }


# Group Clubs

## Club Basics [/api/v1/clubs]

### getAllClubs [GET]
Gets a list of all the clubs available

+ Request

  + Headers

            Content-Type: application/json

### createClub [POST]
Creates a new club

+ Request

  + Headers

            Content-Type: application/json


## Get Club [/api/v1/clubs/{id}]

+ Parameters
    + id (required, integer, `1`) ... The ID of the club you want

### getClub [GET]
Get a specific club by ID

+ Request

  + Headers

            Content-Type: application/json


## Get All Players From Club [/api/v1/clubs/{id}/players]

+ Parameters
    + id (required, integer, `1`) ... The ID of the club you want

### getAllPlayersFromClub [GET]
Get of list of all the players who are in this club

+ Request

  + Headers

            Content-Type: application/json


## Get All Starting Players From Club [/api/v1/clubs/{id}/players/starting]

+ Parameters
    + id (required, integer, `1`) ... The ID of the club you want

### getAllStartingPlayersFromClub [GET]
Get of list of all the players who are marked as starting for this club

+ Request

  + Headers

            Content-Type: application/json


## Get All Benched Players From Club [/api/v1/clubs/{id}/players/benched]

+ Parameters
    + id (required, integer, `1`) ... The ID of the club you want

### getAllBenchedPlayersFromClub [GET]
Get of list of all the players who are not marked as starting for this club

+ Request

  + Headers

            Content-Type: application/json


## Division Membership [/api/v1/clubs/{id}/divisions/{division_id}]

+ Parameters
    + id (required, integer, `1`) ... The ID of the club you want
    + division_id (required, integer, `1`) ... The ID of the division

### joinDivision [GET]
Join the division with the club specified

+ Request

  + Headers

            Content-Type: application/json

### leaveDivision [DELETE]
Leave the division with the club specified

+ Request

  + Headers

            Content-Type: application/json


## Stadium Membership [/api/v1/clubs/{id}/stadiums/{stadium_id}]

+ Parameters
    + id (required, integer, `1`) ... The ID of the club you want
    + stadium_id (required, integer, `1`) ... The ID of the stadium

### joinStadium [GET]
Join the stadium with the club specified

+ Request

  + Headers

            Content-Type: application/json

### leaveStadium [DELETE]
Leave the stadium with the club specified

+ Request

  + Headers

            Content-Type: application/json


## Manager Membership [/api/v1/clubs/{id}/managers/{manager_id}]

+ Parameters
    + id (required, integer, `1`) ... The ID of the club you want
    + manager_id (required, integer, `1`) ... The ID of the manager you want to hire

### hireManager [GET]
Hire the manager specified to the club

+ Request

  + Headers

            Content-Type: application/json

### fireManager [DELETE]
Fire the manager specified from the club

+ Request

  + Headers

            Content-Type: application/json


# Group Divisions

## Division Basics [/api/v1/divisions]

### getAllDivisions [GET]
Gets a list of all the divisions available

+ Request

  + Headers

            Content-Type: application/json

### createDivision [POST]
Creates a new division

+ Request

  + Headers

            Content-Type: application/json


## Get Division [/api/v1/divisions/{id}]

+ Parameters
    + id (required, integer, `1`) ... The ID of the division you want

### getDivision [GET]
Get a specific division by ID

+ Request

  + Headers

            Content-Type: application/json


## Get All Clubs From Division [/api/v1/divisions/{id}/clubs]

+ Parameters
    + id (required, integer, `1`) ... The ID of the division you want

### getAllClubsFromDivision [GET]
Get a list of all the clubs in this division

+ Request

  + Headers

            Content-Type: application/json


## Nation Membership [/api/v1/divisions/{id}/nations/{nation_id}]

+ Parameters
    + id (required, integer, `1`) ... The ID of the division you want
    + nation_id (required, integer, `1`) ... The ID of the nation

### joinNation [GET]
Join the nation with the division specified

+ Request

  + Headers

            Content-Type: application/json

### leaveNation [DELETE]
Leave the nation with the division specified

+ Request

  + Headers

            Content-Type: application/json
